// Top 200+ US Cities for location autocomplete
export const US_CITIES = [
  "New York, NY",
  "Los Angeles, CA",
  "Chicago, IL",
  "Houston, TX",
  "Phoenix, AZ",
  "Philadelphia, PA",
  "San Antonio, TX",
  "San Diego, CA",
  "Dallas, TX",
  "Austin, TX",
  "San Jose, CA",
  "Fort Worth, TX",
  "Jacksonville, FL",
  "Columbus, OH",
  "Charlotte, NC",
  "Indianapolis, IN",
  "San Francisco, CA",
  "Seattle, WA",
  "Denver, CO",
  "Washington, DC",
  "Boston, MA",
  "El Paso, TX",
  "Nashville, TN",
  "Oklahoma City, OK",
  "Las Vegas, NV",
  "Detroit, MI",
  "Portland, OR",
  "Memphis, TN",
  "Louisville, KY",
  "Baltimore, MD",
  "Milwaukee, WI",
  "Albuquerque, NM",
  "Tucson, AZ",
  "Fresno, CA",
  "Sacramento, CA",
  "Kansas City, MO",
  "Atlanta, GA",
  "Colorado Springs, CO",
  "Raleigh, NC",
  "Miami, FL",
  "Long Beach, CA",
  "Virginia Beach, VA",
  "Omaha, NE",
  "Minneapolis, MN",
  "Oakland, CA",
  "Tampa, FL",
  "Tulsa, OK",
  "Arlington, TX",
  "Wichita, KS",
  "Bakersfield, CA",
  "Aurora, CO",
  "New Orleans, LA",
  "Cleveland, OH",
  "Anaheim, CA",
  "Henderson, NV",
  "Honolulu, HI",
  "Riverside, CA",
  "Santa Ana, CA",
  "Corpus Christi, TX",
  "Lexington, KY",
  "San Juan, PR",
  "Stockton, CA",
  "St. Paul, MN",
  "Cincinnati, OH",
  "Greensboro, NC",
  "Pittsburgh, PA",
  "Irvine, CA",
  "St. Louis, MO",
  "Lincoln, NE",
  "Orlando, FL",
  "Durham, NC",
  "Plano, TX",
  "Anchorage, AK",
  "Newark, NJ",
  "Chula Vista, CA",
  "Fort Wayne, IN",
  "Jersey City, NJ",
  "Chandler, AZ",
  "Madison, WI",
  "Lubbock, TX",
  "Scottsdale, AZ",
  "Reno, NV",
  "Buffalo, NY",
  "Gilbert, AZ",
  "Glendale, AZ",
  "North Las Vegas, NV",
  "Winston-Salem, NC",
  "Chesapeake, VA",
  "Norfolk, VA",
  "Fremont, CA",
  "Garland, TX",
  "Irving, TX",
  "Hialeah, FL",
  "Richmond, VA",
  "Boise, ID",
  "Spokane, WA",
  "Baton Rouge, LA",
  "Tacoma, WA",
  "Fontana, CA",
  "San Bernardino, CA",
  "Modesto, CA",
  "Des Moines, IA",
  "Rochester, NY",
  "Moreno Valley, CA",
  "Oxnard, CA",
  "Yonkers, NY",
  "Columbus, GA",
  "Augusta, GA",
  "Little Rock, AR",
  "Amarillo, TX",
  "Salt Lake City, UT",
  "Montgomery, AL",
  "Huntington Beach, CA",
  "Grand Rapids, MI",
  "Akron, OH",
  "Tallahassee, FL",
  "Cape Coral, FL",
  "Grand Prairie, TX",
  "Port St. Lucie, FL",
  "Overland Park, KS",
  "Tempe, AZ",
  "McKinney, TX",
  "Mobile, AL",
  "Knoxville, TN",
  "Worcester, MA",
  "Frisco, TX",
  "Brownsville, TX",
  "Newport News, VA",
  "Chattanooga, TN",
  "Fort Lauderdale, FL",
  "Santa Clarita, CA",
  "Santa Rosa, CA",
  "Rancho Cucamonga, CA",
  "Oceanside, CA",
  "Ontario, CA",
  "Garden Grove, CA",
  "Vancouver, WA",
  "Elk Grove, CA",
  "Sioux Falls, SD",
  "Pembroke Pines, FL",
  "Salem, OR",
  "Lancaster, CA",
  "Corona, CA",
  "Eugene, OR",
  "Palmdale, CA",
  "McKinney, TX",
  "Salinas, CA",
  "Fort Collins, CO",
  "Cary, NC",
  "Pasadena, TX",
  "Hayward, CA",
  "Pomona, CA",
  "Sunnyvale, CA",
  "Escondido, CA",
  "Killeen, TX",
  "Alexandria, VA",
  "Torrance, CA",
  "Lakewood, CO",
  "Roseville, CA",
  "Hollywood, FL",
  "Paterson, NJ",
  "Joliet, IL",
  "Bridgeport, CT",
  "Rockford, IL",
  "Pasadena, CA",
  "Naperville, IL",
  "Savannah, GA",
  "Mesquite, TX",
  "Syracuse, NY",
  "Dayton, OH",
  "Orange, CA",
  "Fullerton, CA",
  "McAllen, TX",
  "Bellevue, WA",
  "Murfreesboro, TN",
  "Olathe, KS",
  "Columbia, SC",
  "Thornton, CO",
  "Carrollton, TX",
  "Costa Mesa, CA",
  "Coral Springs, FL",
  "Surprise, AZ",
  "Sterling Heights, MI",
  "Charleston, SC",
  "Topeka, KS",
  "New Haven, CT",
  "Elizabeth, NJ",
  "Thousand Oaks, CA",
  "Visalia, CA",
  "Gainesville, FL",
  "Simi Valley, CA",
  "Stamford, CT",
  "Hartford, CT",
  "Concord, CA",
  "Kent, WA",
  "Lafayette, LA",
  "Denton, TX",
  "Cedar Rapids, IA",
  "Berkeley, CA",
  "Santa Clara, CA",
  "Cambridge, MA",
  "Round Rock, TX",
  "Ann Arbor, MI",
  "Boulder, CO",
  "Clearwater, FL",
  "The Woodlands, TX",
  "Evanston, IL",
  "Richardson, TX",
  "Remote",
  "Hybrid"
]